[project]
name = "my-first-nn"
version = "0.1.0"
description = "My first neural network in Python"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "scikit-learn>=1.8.0",
]
